# Automatically sync main branch to GitHub on tag

trigger:
  tags:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-22.04'

steps:
  - checkout: self
    fetchTags: true

  - script: |
      git remote add github 'https://$(GITHUB_USER):$(GITHUB_PAT)@github.com/$(GITHUB_REPO)'
      git push github main
      git push github $(Build.SourceBranchName)
    displayName: 'Sync repository with GitHub'
