# Automatically sync main branch to GitHub

trigger:
  branches:
    include:
      - 'main'

pool:
  vmImage: 'ubuntu-22.04'

steps:
  - checkout: self
    fetchTags: true

  - script: |
      git switch $(Build.SourceBranchName)
      git remote add github 'https://$(GITHUB_USER):$(GITHUB_PAT)@github.com/$(GITHUB_REPO)'
      git push github $(Build.SourceBranchName)
    displayName: 'Sync repository with GitHub'
