# Automatically sync main branch and tags to GitHub on tag

trigger:
  tags:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-22.04'

resources:
  repositories:
    - repository: this
      type: git
      name: portale-fatturazione-be
      ref: main

steps:
  - checkout: this
    fetchTags: true

  - script: |
      git remote add github 'https://$(GITHUB_USER):$(GITHUB_PAT)@github.com/$(GITHUB_REPO)'
      git push github main
      git push github $(Build.SourceBranchName)
    displayName: 'Sync repository with GitHub'
